# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
sudo: required
matrix:
  include:
    - name: Python 2.7
      python: 2.7
      env: python_version=2.7

    - name: Python 3.5
      python: 3.5
      env: python_version=3.5

    - name: Python 3.6
      python: 3.6
      env: python_version=3.6

    - name: Python 3.7
      python: 3.7
      env: python_version=3.7
  allow_failures:
    - python: 2.7
    - python: 3.5

cache:
  directories:
    - eggs
install:
  - pip install -e .[test]
  - pip install codecov
  - sleep 1
script:
  - git submodule update --init --recursive
  - make clean
  - pytest fhir/resources/STU3/tests
  - pytest -s --cov=fhir/resources/tests -s --tb=native -v --cov-report term-missing --cov-append fhir/resources/tests
after_success:
  - codecov
